/* GENERATED by python/gen_seq_flags.py - DO NOT EDIT.
 *
 * Copyright 2026 Logan W.
 * SPDX-License-Identifier: Apache-2.0
 *
 * The sequencer header's `flags` word, by name. The NUMBERS live in
 * cft.h, where each one is documented; this is the name table, which
 * is the part that used to be transcribed into every refusal that
 * mentioned a flag - and which drifted to three different revisions
 * at once before it was generated.
 *
 * Render from YOUR OWN mask, never from every defined bit: the
 * assembler accepts fewer flags than the loader, and a message that
 * names a flag its mask refuses is the bug this file prevents.
 */
#ifndef CFT_SEQ_FLAGS_H
#define CFT_SEQ_FLAGS_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bounded append; returns the new length. Separate so the renderer
 * below stays readable, and static inline so a translation unit that
 * never calls it warns about nothing. */
static inline size_t
cft_seq_flag_append_(char *buf, size_t n, size_t used, const char *s)
{
    size_t len;
    if (n == 0u || used >= n - 1u)
        return used;
    len = strlen(s);
    if (len > n - used - 1u)
        len = n - used - 1u;
    memcpy(buf + used, s, len);
    buf[used + len] = '\0';
    return used + len;
}

/* The names in `mask`, low bit first, as English: "A", "A and B",
 * "A, B and C". Returns `buf`, always NUL-terminated when n > 0.
 * `mask` with no known bit renders "none". */
static inline const char *
cft_seq_flag_names(uint32_t mask, char *buf, size_t n)
{
    static const struct { uint32_t bit; const char *name; } defs[] = {
        { 0x00000001u, "BANK_EXT" },
        { 0x00000002u, "SCRATCH_IO" },
        { 0x00000004u, "SCRATCH_STRICT" },
    };
    const size_t ndefs = sizeof defs / sizeof defs[0];
    size_t i, used = 0u, count = 0u, seen = 0u;

    if (n == 0u)
        return buf;
    buf[0] = '\0';
    for (i = 0u; i < ndefs; i++)
        if (mask & defs[i].bit)
            count++;
    if (count == 0u)
        return (cft_seq_flag_append_(buf, n, 0u, "none"), buf);
    for (i = 0u; i < ndefs; i++) {
        if (!(mask & defs[i].bit))
            continue;
        if (seen != 0u)
            used = cft_seq_flag_append_(buf, n, used,
                                        seen + 1u == count ? " and " : ", ");
        used = cft_seq_flag_append_(buf, n, used, defs[i].name);
        seen++;
    }
    return buf;
}

/* Enough room for every defined name plus its separators. */
#define CFT_SEQ_FLAG_NAMES_MAX 43u

#ifdef __cplusplus
}
#endif
#endif /* CFT_SEQ_FLAGS_H */
