/* Copyright 2026 Logan W.
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by host/tools/gen_mp_consts.py - do not edit.
 *
 * The transcendental evaluator's constants, each truncated
 * toward zero to exactly 1088 bits: value == M * 2^exp with M the
 * little-endian limb array below, so every stored constant is
 * at most one unit in the last place BELOW the true value and
 * never above it.
 *
 * Regenerate with `python3 host/tools/gen_mp_consts.py`;
 * python/tests/test_mp_consts.py fails if this file and the
 * script ever disagree, and cft_mp_consts_selfcheck() re-proves
 * the two reciprocal relations at runtime.
 */

#ifndef CFT_MP_CONSTS_H
#define CFT_MP_CONSTS_H

#include <stdint.h>

#define CFT_MP_CONST_BITS  1088
#define CFT_MP_CONST_LIMBS 34

/* ln 2 */
#define CFT_MP_LN2_EXP (-1088)
static const uint32_t cft_mp_ln2_limbs[CFT_MP_CONST_LIMBS] = {
    0xfb5bfb90u, 0x07f4ca11u, 0x0f3fd5c6u, 0xda2d97c5u,
    0x2f20e3a2u, 0x655fa187u, 0x38303248u, 0xf5dfa6bdu,
    0x9d6548cau, 0x72ce87b1u, 0x7657f74bu, 0x256fa0ecu,
    0xb136603bu, 0xb9ea9bc3u, 0x317c387eu, 0x1acbda11u,
    0x224ae8c5u, 0x3e96ca16u, 0x1169b825u, 0x27573b29u,
    0xc1382144u, 0xed2eae35u, 0x4afa1b10u, 0x559552fbu,
    0x6debac98u, 0xe7b87620u, 0x8baafa2bu, 0x8a0d175bu,
    0x7298b62du, 0x40f34326u, 0x03f2f6afu, 0xc9e3b398u,
    0xd1cf79abu, 0xb17217f7u,
};

/* 1 / ln 2 */
#define CFT_MP_LOG2E_EXP (-1087)
static const uint32_t cft_mp_log2e_limbs[CFT_MP_CONST_LIMBS] = {
    0x058eba50u, 0x2650b6d1u, 0xae30a173u, 0x612f08fbu,
    0x8cd5db8fu, 0xce7e2035u, 0x4679c940u, 0x278ccf08u,
    0x6f5b4967u, 0x199a9483u, 0xab63253cu, 0x8d1cf457u,
    0x3a828546u, 0x0b5ebbbfu, 0x79d5a206u, 0xb21b43d5u,
    0x2617d9d5u, 0x2fe29493u, 0x53df39b3u, 0xc4bfaf03u,
    0x0c4a909fu, 0xea90b9e6u, 0xc16be0b3u, 0x24d92f75u,
    0x55176cd6u, 0xde1c43f7u, 0xd1a13247u, 0x8b25166cu,
    0xdd695a58u, 0xeb577aa8u, 0x691d3e88u, 0xbe87fed0u,
    0x5c17f0bbu, 0xb8aa3b29u,
};

/* ln 10 */
#define CFT_MP_LN10_EXP (-1086)
static const uint32_t cft_mp_ln10_limbs[CFT_MP_CONST_LIMBS] = {
    0xad3aee98u, 0xe2478fcau, 0x9305e981u, 0x469ea58eu,
    0xd5ede20fu, 0x5b08b057u, 0x44789c4fu, 0x8e93368du,
    0x23605085u, 0xca67b35bu, 0xd219c7bbu, 0x5161bb49u,
    0x4ab3c6fau, 0xef66ceb0u, 0xb0d831fbu, 0x765aa6c3u,
    0x8a8c911eu, 0x782cf8a2u, 0x02e516d6u, 0xfb8f7884u,
    0x410be2dau, 0x2c622418u, 0x2c5f0d68u, 0xcc70cbc0u,
    0xb1a8105cu, 0x962f02d7u, 0x01f02d72u, 0x83c61e82u,
    0xda5df90eu, 0xe28fecf9u, 0x82d30a28u, 0xea56d62bu,
    0xaaa8ac16u, 0x935d8dddu,
};

/* 1 / ln 10 */
#define CFT_MP_LOG10E_EXP (-1089)
static const uint32_t cft_mp_log10e_limbs[CFT_MP_CONST_LIMBS] = {
    0x50c65e94u, 0xd121adc6u, 0xecdb1f6cu, 0xb3fe40c2u,
    0x27c968ebu, 0xd794d64fu, 0xcc51f934u, 0x648ecc89u,
    0xe68c04d4u, 0x5430212au, 0x2f3739d5u, 0x50b36dedu,
    0x42c84d6au, 0x658b61eau, 0x8c1dc4dau, 0x40072005u,
    0x48d06ff9u, 0x4356bd19u, 0xc8cda7b3u, 0x6fa2b8d2u,
    0xfd38dcbcu, 0x18ce3bd9u, 0xc6464a15u, 0x92235592u,
    0x1402f3f2u, 0x75424efau, 0xf78ea53cu, 0x3a3f2d44u,
    0x45c9a202u, 0x3ee34602u, 0xad33dc32u, 0x355baaafu,
    0x37287195u, 0xde5bd8a9u,
};

#endif /* CFT_MP_CONSTS_H */
