#!/usr/bin/env python3
"""Generate a place-and-route harness for cft_krnl from its own port list.

nextpnr has no out-of-context mode, and cft_krnl's 1,558 port bits cannot
all be package pins (xc7k325tffg900 bonds 500 user I/O). The harness drives
every kernel input from one register chain fed by a pin, and XOR-folds
every kernel output, pipelined, into one pin - so no input is constant and
no output unobserved, and synthesis prunes nothing a real platform would
keep. The widths are READ from rtl/cft_krnl.sv, never typed here: a
hand-written harness is where a silent truncation would come from.

    python gen_harness.py <rtl/cft_krnl.sv> <out.sv> [NAME=VALUE ...]

NAME=VALUE overrides a kernel parameter, VALUE in SystemVerilog literal
form (MUL_PASSES=1 FUSE_NORM=1'b0 ...); with none, the `board`
configuration (tb/Makefile BOARD_PARAMS). A name the kernel does not
declare is refused.

Prints the input and output widths it derived, which must match the
standalone synthesis's IBUF/OBUF counts less clock and reset (857 / 699).
"""
import re
import sys

BEAT_BITS = 256          # cft_krnl's default; the board configuration keeps it
BOARD = {"MUL_PASSES": "10", "FUSE_NORM": "1'b1", "FUSE_ALIGN": "1'b1"}
SKIP = {"ap_clk", "ap_rst_n"}

for arg in sys.argv[3:]:
    name, sep, value = arg.partition("=")
    if not sep or not value:
        sys.exit(f"not NAME=VALUE: {arg!r}")
    BOARD[name] = value

src = open(sys.argv[1], encoding="utf-8").read()
# The port list: from the ") (" that closes the parameter list to the
# "\n);" that closes the ports - searched AFTER the opening, because the
# parameter comments contain ");" of their own.
header = src[src.index("module cft_krnl"):]
declared = set(re.findall(r"\bparameter\s+(?:\w+\s+)?(\w+)\s*=", header[:header.index(") (")]))
unknown = set(BOARD) - declared
if unknown:
    sys.exit(f"cft_krnl declares no parameter named {sorted(unknown)}; it declares {sorted(declared)}")
start = header.index(") (") + 3
header = header[start:header.index("\n);", start)]
ports = []
for m in re.finditer(r"\b(input|output)\s+logic\s*(\[[^\]]+\])?\s*(\w+)", header):
    direction, rng, name = m.group(1), m.group(2), m.group(3)
    if rng is None:
        width = 1
    else:
        hi, lo = rng[1:-1].split(":")
        env = {"BEAT_BITS": BEAT_BITS}
        width = int(eval(hi, {}, env)) - int(eval(lo, {}, env)) + 1
    ports.append((direction, name, width))

ins = [(n, w) for d, n, w in ports if d == "input" and n not in SKIP]
outs = [(n, w) for d, n, w in ports if d == "output"]
missing = SKIP - {n for _, n, _ in ports}
if missing:
    sys.exit(f"clock/reset ports not found: {missing}")
in_w = sum(w for _, w in ins)
out_w = sum(w for _, w in outs)

conn, off = [], 0
for n, w in ins:
    conn.append(f"    .{n}(kin[{off + w - 1}:{off}]),")
    off += w
off = 0
for n, w in outs:
    conn.append(f"    .{n}(kout[{off + w - 1}:{off}]),")
    off += w

g1 = -(-out_w // 6)
g2 = -(-g1 // 6)
params = ", ".join(f".{k}({v})" for k, v in BOARD.items())

sv = f"""// GENERATED by gen_harness.py from rtl/cft_krnl.sv - do not edit.
// A place-and-route harness, not a platform: its pins are the KC705
// demo's (openXC7/demo-projects blinky-kc705, same package), and the
// bitstream it produces must never be loaded onto a board.
// Kernel inputs: {len(ins)} ports, {in_w} bits. Outputs: {len(outs)} ports, {out_w} bits.
`default_nettype none
module cft_pnr_harness (
    input  wire clk_p,
    input  wire clk_n,
    input  wire rst_n_pin,
    input  wire sin,
    output wire sout
);
  wire clk_ibufg, clk;
  IBUFDS ibuf_inst (.I(clk_p), .IB(clk_n), .O(clk_ibufg));
  BUFG   bufg_inst (.I(clk_ibufg), .O(clk));

  reg [1:0] rst_sync = 2'b00;
  always @(posedge clk) rst_sync <= {{rst_sync[0], rst_n_pin}};

  // Every kernel input from its own register: one chain, one pin.
  reg [{in_w - 1}:0] kin = {in_w}'d0;
  always @(posedge clk) kin <= {{kin[{in_w - 2}:0], sin}};

  wire [{out_w - 1}:0] kout;

  cft_krnl #({params}) u_krnl (
    .ap_clk(clk),
    .ap_rst_n(rst_sync[1]),
{chr(10).join(conn).rstrip(',')}
  );

  // Every kernel output observed: XOR-folded six at a time, registered at
  // each level, so the fold is never the critical path.
  wire [{g1 * 6 - 1}:0] p1 = {{{{{g1 * 6 - out_w}{{1'b0}}}}, kout}};
  reg  [{g1 - 1}:0] x1;
  wire [{g2 * 6 - 1}:0] p2 = {{{{{g2 * 6 - g1}{{1'b0}}}}, x1}};
  reg  [{g2 - 1}:0] x2;
  reg  x3;
  integer i;
  always @(posedge clk) begin
    for (i = 0; i < {g1}; i = i + 1) x1[i] <= ^p1[i*6 +: 6];
    for (i = 0; i < {g2}; i = i + 1) x2[i] <= ^p2[i*6 +: 6];
    x3 <= ^x2;
  end
  assign sout = x3;
endmodule
`default_nettype wire
"""
open(sys.argv[2], "w", encoding="utf-8").write(sv)
print(f"inputs  {len(ins)} ports {in_w} bits")
print(f"outputs {len(outs)} ports {out_w} bits")
print(f"fold    {out_w} -> {g1} -> {g2} -> 1")
