# Copyright 2026 Logan W.
# SPDX-License-Identifier: Apache-2.0
"""Emit host/src/mp_consts.h - the transcendental evaluator's constants.

    python3 host/tools/gen_mp_consts.py                 # write the header
    python3 host/tools/gen_mp_consts.py --check         # verify it

Four numbers, at 1088 bits each: ln 2, log2 e, ln 10 and log10 e. They
are DERIVED, never transcribed. A hand-typed constant has been wrong in
this project three times, and a wrong constant here would not crash -
it would return a plausible number with a silently wrong low bit, which
is the exact failure mode this library exists to make impossible.

So the header is generated from mpmath, `--check` regenerates it and
compares byte for byte (python/tests/test_mp_consts.py runs that on
every test run), and the C carries its own arithmetic self-test as
well: cft_mp_consts_selfcheck() multiplies ln2 by log2e and ln10 by
log10e and requires both products to be 1 to within a few units in the
last place. The Python check catches a stale header; the C check
catches a corrupted or truncated one at the point of use.

Why 1088 and not "enough": the widest working precision the evaluator
can reach is 832 bits, plus 32 bits of guard, plus up to 19 bits of
headroom for the argument-reduction multiple k - 883 bits in the worst
case any format can ask for. 1088 is the next multiple of 32 above
that with a comfortable margin, and being a whole number of limbs
means the header is a plain uint32_t array with no partial word.
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "host" / "src" / "mp_consts.h"

BITS = 1088
LIMBS = BITS // 32


def truncated(value, bits):
    """(limbs, exp) with value ~= M * 2^exp, M exactly `bits` wide and
    truncated toward zero. mpmath's mpf is a dyadic rational, so the
    only rounding here is the one this function performs."""
    import mpmath
    mpmath.mp.prec = bits + 64
    v = value()
    man, exp = mpmath.libmp.to_man_exp(v._mpf_)
    man = int(man)
    assert man > 0
    shift = bits - man.bit_length()
    if shift >= 0:
        man <<= shift
    else:
        man >>= -shift
    exp -= shift
    assert man.bit_length() == bits
    limbs = [(man >> (32 * i)) & 0xFFFFFFFF for i in range(LIMBS)]
    return limbs, exp


def constants():
    import mpmath
    return [
        ("LN2", "ln 2", lambda: mpmath.log(2)),
        ("LOG2E", "1 / ln 2", lambda: 1 / mpmath.log(2)),
        ("LN10", "ln 10", lambda: mpmath.log(10)),
        ("LOG10E", "1 / ln 10", lambda: 1 / mpmath.log(10)),
    ]


def render():
    lines = []
    add = lines.append
    add("/* Copyright 2026 Logan W.")
    add(" * SPDX-License-Identifier: Apache-2.0")
    add(" *")
    add(" * GENERATED by host/tools/gen_mp_consts.py - do not edit.")
    add(" *")
    add(" * The transcendental evaluator's constants, each truncated")
    add(f" * toward zero to exactly {BITS} bits: value == M * 2^exp with M the")
    add(" * little-endian limb array below, so every stored constant is")
    add(" * at most one unit in the last place BELOW the true value and")
    add(" * never above it.")
    add(" *")
    add(" * Regenerate with `python3 host/tools/gen_mp_consts.py`;")
    add(" * python/tests/test_mp_consts.py fails if this file and the")
    add(" * script ever disagree, and cft_mp_consts_selfcheck() re-proves")
    add(" * the two reciprocal relations at runtime.")
    add(" */")
    add("")
    add("#ifndef CFT_MP_CONSTS_H")
    add("#define CFT_MP_CONSTS_H")
    add("")
    add("#include <stdint.h>")
    add("")
    add(f"#define CFT_MP_CONST_BITS  {BITS}")
    add(f"#define CFT_MP_CONST_LIMBS {LIMBS}")
    add("")
    for name, desc, fn in constants():
        limbs, exp = truncated(fn, BITS)
        add(f"/* {desc} */")
        add(f"#define CFT_MP_{name}_EXP ({exp})")
        add(f"static const uint32_t cft_mp_{name.lower()}_limbs"
            f"[CFT_MP_CONST_LIMBS] = {{")
        for i in range(0, LIMBS, 4):
            row = ", ".join(f"0x{v:08x}u" for v in limbs[i:i + 4])
            add(f"    {row},")
        add("};")
        add("")
    add("#endif /* CFT_MP_CONSTS_H */")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed header instead of writing it")
    ap.add_argument("--out", default=str(HEADER))
    args = ap.parse_args()
    text = render()
    out = Path(args.out)
    if args.check:
        if not out.exists():
            print(f"{out}: missing", file=sys.stderr)
            return 1
        have = out.read_text()
        if have != text:
            print(f"{out}: does NOT match what the generator emits - "
                  "regenerate it (python3 host/tools/gen_mp_consts.py)",
                  file=sys.stderr)
            return 1
        print(f"{out}: matches the generator, "
              f"{len(constants())} constants at {BITS} bits")
        return 0
    out.write_text(text)
    print(f"{out}: {len(constants())} constants at {BITS} bits")
    return 0


if __name__ == "__main__":
    sys.exit(main())
