#!/usr/bin/env python3
# Copyright 2026 Logan W.
# SPDX-License-Identifier: Apache-2.0
"""Generate host/src/divfull_images.h from cft_golden/divfull.py.

The whole-divide and whole-square-root programs (docs/ROADMAP.md,
workload ask 8) are ~200 instructions a format with constant indices
past 15 and registers past 15, and libcft has no Python at build time.
The library's existing divide route (host/src/divsqrt.c, sq_emit)
hand-ports seqprogs.py's fifty instructions into C emitter calls;
doing that again for two hundred would be a second implementation of
the same schedule kept in sync by eye, which is the kind of
transcription this repo has been bitten by three times. So the IMAGE
is generated: the bytes Program.to_bytes() produces, one array a
format and a program, and beside each the bank words that do not
depend on the rounding attribute - all but the last five - packed the
way the device reads a bank. The library appends the five mode words
itself (a 1 in the caller's attribute's slot) and never derives a
constant.

`--check` regenerates and compares, so the committed header cannot
drift from the model: verify/run.sh's `generated` stage runs it.

    python python/gen_divfull.py            write the header
    python python/gen_divfull.py --check    exit 1 if it drifted
"""
import io
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from cft_golden import FP32, FP64, FP128, FP256  # noqa: E402
from cft_golden import divfull  # noqa: E402
from cft_golden.softfloat import RND_RNE  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADER = ROOT / "host" / "src" / "divfull_images.h"
FORMATS = (FP32, FP64, FP128, FP256)
NFIXED = divfull.N_CONSTS - divfull.N_MODES
NFIXED_SQRT = divfull.N_CONSTS_SQRT - divfull.N_MODES

PROGRAMS = (
    ("divide", "divfull", divfull.div_full_program_for, divfull.bank,
     NFIXED, divfull.N_CONSTS),
    ("square root", "sqrtfull", divfull.sqrt_full_program_for,
     divfull.bank_sqrt, NFIXED_SQRT, divfull.N_CONSTS_SQRT),
)


def c_bytes(name, data):
    out = io.StringIO()
    w = out.write
    w("static const uint8_t %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), 12):
        w("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",\n")
    w("};\n")
    return out.getvalue()


def render():
    out = io.StringIO()
    w = out.write
    w("/* GENERATED by python/gen_divfull.py from python/cft_golden/divfull.py.\n")
    w(" * Do not edit: `python python/gen_divfull.py` rewrites it and\n")
    w(" * `--check` (verify/run.sh, the generated stage) refuses drift.\n")
    w(" *\n")
    w(" * One image a format for the whole divide and one for the whole\n")
    w(" * square root - sequencer programs, BANK_EXT, two deposits a lane\n")
    w(" * (result, flag word) - and beside each the bank words that do not\n")
    w(" * depend on the rounding attribute (%d and %d of them),\n"
      % (NFIXED, NFIXED_SQRT))
    w(" * little-endian at the format's width, in index order. The library\n")
    w(" * appends the five mode words (RNE, RTZ, RDN, RUP, RMM: a 1 in the\n")
    w(" * caller's slot) and runs the image with cft_program_run_bank. The\n")
    w(" * image's own SHA-256 is a stable name for the schedule; the run's\n")
    w(" * digest covers the bank too. */\n")
    w("#ifndef CFT_DIVFULL_IMAGES_H\n#define CFT_DIVFULL_IMAGES_H\n\n")
    w("#include <stddef.h>\n#include <stdint.h>\n\n")
    w("#define CFT_DIVFULL_NCONSTS  %d\n" % divfull.N_CONSTS)
    w("#define CFT_DIVFULL_NFIXED   %d\n" % NFIXED)
    w("#define CFT_SQRTFULL_NCONSTS %d\n" % divfull.N_CONSTS_SQRT)
    w("#define CFT_SQRTFULL_NFIXED  %d\n" % NFIXED_SQRT)
    w("#define CFT_DIVFULL_NMODES   %d\n" % divfull.N_MODES)
    w("#define CFT_DIVFULL_NDEPOSITS 2\n\n")
    w("typedef struct {\n    const uint8_t *image;\n    size_t image_bytes;\n"
      "    const uint8_t *bank;         /* the fixed words */\n"
      "    size_t n_consts, n_fixed;\n"
      "} cft_divfull_entry;\n\n")
    for kind, tag, prog_for, bank_for, nfixed, nconsts in PROGRAMS:
        for fmt in FORMATS:
            prog = prog_for(fmt)
            image = prog.to_bytes()
            esz = fmt.width // 8
            fixed = bank_for(fmt, RND_RNE)[:nfixed]
            bank = b"".join(v.to_bytes(esz, "little") for v in fixed)
            w("/* the %s, %s: %d instructions, %d bytes */\n"
              % (kind, fmt.name, len(prog.insns), len(image)))
            w(c_bytes("cft_%s_image_%s" % (tag, fmt.name), image))
            w(c_bytes("cft_%s_bank_%s" % (tag, fmt.name), bank))
            w("\n")
        w("/* Indexed by cft_format: fp32, fp64, fp128, fp256. */\n")
        w("static const cft_divfull_entry cft_%s_images[4] = {\n" % tag)
        for fmt in FORMATS:
            w("    { cft_%s_image_%s, sizeof cft_%s_image_%s, cft_%s_bank_%s, "
              "%d, %d },\n" % (tag, fmt.name, tag, fmt.name, tag, fmt.name,
                               nconsts, nfixed))
        w("};\n\n")
    w("#endif /* CFT_DIVFULL_IMAGES_H */\n")
    return out.getvalue()


def main(argv):
    text = render()
    if "--check" in argv:
        if not HEADER.is_file():
            print("gen_divfull: %s is missing" % HEADER)
            return 1
        have = HEADER.read_text(encoding="utf-8")
        if have != text:
            print("gen_divfull: STALE %s - run python python/gen_divfull.py"
                  % HEADER.relative_to(ROOT))
            return 1
        print("gen_divfull: host/src/divfull_images.h matches divfull.py")
        return 0
    io.open(HEADER, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d bytes)" % (HEADER.relative_to(ROOT), len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
