# Copyright 2026 Logan W.
# SPDX-License-Identifier: Apache-2.0
"""Generate rtl/cft_seed_rom.svh from the golden model's seed tables.

The model's _seed_recip_entry/_seed_rsqrt_entry ARE the specification
(proven to the 2^-8.5 bound by test_seeds.py, exhaustively). This
script derives the hardware ROM from them - per the standing rule that
constants are derived, never transcribed, because hand-typed magic
numbers have been wrong here before. tests/test_seed_rom_sync.py
regenerates the content and compares it to the committed file, so the
ROM cannot drift from the model without a test failing.

Run from the repository root:  python python/gen_seed_rom.py
"""

import io
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cft_golden.softfloat import (  # noqa: E402
    SEED_INDEX_BITS, SEED_TABLE_SIZE,
    _seed_recip_entry, _seed_rsqrt_entry,
)


def render() -> str:
    recip = [_seed_recip_entry(i) for i in range(SEED_TABLE_SIZE)]
    rsqrt = [_seed_rsqrt_entry(j) for j in range(2 * SEED_TABLE_SIZE)]
    # Both tables are normalised by construction: msb always set, never
    # a power of two - which is what lets the RTL skip any
    # normalisation case-split.
    assert all((1 << 17) < r < (1 << 18) for r in recip)
    assert all((1 << 16) < r < (1 << 17) for r in rsqrt)

    out = io.StringIO()
    w = out.write
    w("// GENERATED by python/gen_seed_rom.py - DO NOT EDIT.\n")
    w("// The golden model's seed-table functions are the specification;\n")
    w("// tests/test_seed_rom_sync.py fails if this file drifts from them.\n")
    w("//\n")
    w("// SEED_RECIP[i]: nearest integer to 2^18 / (1 + (i + 1/2)/2^9),\n")
    w("//   entries in (2^17, 2^18): 18 bits, msb always set.\n")
    w("// SEED_RSQRT[{odd, i}]: nearest integer to 2^17 / sqrt(mid),\n")
    w("//   mid = (1 + (i + 1/2)/2^9) * 2^odd, entries in (2^16, 2^17).\n")
    w("//   17 bits, msb always set.\n")
    w("// Relative error < 2^-8.5, proven exhaustively in test_seeds.py.\n\n")

    # Case tables, not a flat vector with a variable part-select. The
    # flat form was chosen because Icarus rejects unpacked-array
    # assignment patterns for localparams - but `SEED_P[i*18 +: 18]`
    # asks synthesis for i*18 followed by a variable shift of a
    # 9216-bit constant, and Vivado obliges: a DSP48 multiply per lane
    # (the fifteen DPIP-2 items), its 14-bit product fanning out to
    # ~460 loads, all combinational between the operand bus and S0.
    # That was the critical path of every routed build since the seeds
    # landed, including the ones retiming could not close. A case in a
    # function is a ROM - each output bit a 9- or 10-input function of
    # the index, no multiply, no shifter - and it elaborates in Icarus,
    # Yosys 0.33, Verilator and Vivado alike (measured 2026-09-02:
    # seedop 85,264/85,264 under Icarus and Verilator, kernel lint
    # under Yosys).
    w("// Case tables, not a variable part-select of one flat vector:\n")
    w("// the part-select form costs a DSP48 multiply (index*width)\n")
    w("// feeding a wide shifter, and that multiply sat on the critical\n")
    w("// path of every routed build. A case is a ROM.\n\n")

    w("function automatic bit [17:0] seed_recip(input bit [8:0] i);\n")
    w("  case (i)\n")
    for i, r in enumerate(recip):
        w(f"    9'd{i}: seed_recip = 18'd{r};\n")
    w("    default: seed_recip = 18'd0;  // unreachable: every index is listed\n")
    w("  endcase\n")
    w("endfunction\n\n")

    w("function automatic bit [16:0] seed_rsqrt(input bit [9:0] j);\n")
    w("  case (j)\n")
    for j, r in enumerate(rsqrt):
        w(f"    10'd{j}: seed_rsqrt = 17'd{r};\n")
    w("    default: seed_rsqrt = 17'd0;  // unreachable: every index is listed\n")
    w("  endcase\n")
    w("endfunction\n")
    return out.getvalue()


if __name__ == "__main__":
    text = render()
    dest = Path(__file__).resolve().parents[1] / "rtl" / "cft_seed_rom.svh"
    io.open(dest, "w", encoding="utf-8", newline="\n").write(text)
    print(f"wrote {dest} ({len(text)} bytes)")
