#!/usr/bin/env python3
# Copyright 2026 Logan W.
# SPDX-License-Identifier: Apache-2.0
"""Generate host/include/cft_seq_flags.h, and prove cft.h agrees with it.

WHY THIS EXISTS. On 2026-09-11 the list of defined header flags was
written out by hand in eight places and had drifted to three revisions
at once - seq.py knew three flags, asm.py and the whole C side two, and
docs/HOSTAPI.md one while calling itself the list "in full". Two of the
eight were in cft_golden/, so the authority disagreed with itself.

WHAT IS GENERATED AND WHAT IS NOT. The numbering stays hand-written in
host/include/cft.h: it is the public contract and each macro carries a
paragraph of prose that a generator would flatten. What is generated is
the NAME TABLE, which is the part that was transcribed, so a refusal can
render the flags its own mask accepts instead of naming a list somebody
typed. `--check` then proves cft.h and the golden model assign the same
bits, which is the agreement that actually matters.

The check is Python rather than a C _Static_assert on purpose: the host
builds -std=c99 -Wpedantic, and this header is also compiled by avr-gcc
through the vendored Arduino copy. A C11 construct would be a portability
bill for a check that reads better here anyway.

    python python/gen_seq_flags.py            write the header
    python python/gen_seq_flags.py --check    fail if it or cft.h drifted
"""
import io
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from cft_golden.seqflags import FLAG_TABLE  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADER = ROOT / "host" / "include" / "cft_seq_flags.h"
PUBLIC = ROOT / "host" / "include" / "cft.h"


def render():
    out = io.StringIO()
    w = out.write
    w("/* GENERATED by python/gen_seq_flags.py - DO NOT EDIT.\n")
    w(" *\n")
    w(" * Copyright 2026 Logan W.\n")
    w(" * SPDX-License-Identifier: Apache-2.0\n")
    w(" *\n")
    w(" * The sequencer header's `flags` word, by name. The NUMBERS live in\n")
    w(" * cft.h, where each one is documented; this is the name table, which\n")
    w(" * is the part that used to be transcribed into every refusal that\n")
    w(" * mentioned a flag - and which drifted to three different revisions\n")
    w(" * at once before it was generated.\n")
    w(" *\n")
    w(" * Render from YOUR OWN mask, never from every defined bit: the\n")
    w(" * assembler accepts fewer flags than the loader, and a message that\n")
    w(" * names a flag its mask refuses is the bug this file prevents.\n")
    w(" */\n")
    w("#ifndef CFT_SEQ_FLAGS_H\n")
    w("#define CFT_SEQ_FLAGS_H\n\n")
    w("#include <stddef.h>\n")
    w("#include <stdint.h>\n")
    w("#include <string.h>\n\n")
    w("#ifdef __cplusplus\n")
    w('extern "C" {\n')
    w("#endif\n\n")

    w("/* Bounded append; returns the new length. Separate so the renderer\n")
    w(" * below stays readable, and static inline so a translation unit that\n")
    w(" * never calls it warns about nothing. */\n")
    w("static inline size_t\n")
    w("cft_seq_flag_append_(char *buf, size_t n, size_t used, const char *s)\n")
    w("{\n")
    w("    size_t len;\n")
    w("    if (n == 0u || used >= n - 1u)\n")
    w("        return used;\n")
    w("    len = strlen(s);\n")
    w("    if (len > n - used - 1u)\n")
    w("        len = n - used - 1u;\n")
    w("    memcpy(buf + used, s, len);\n")
    w("    buf[used + len] = '\\0';\n")
    w("    return used + len;\n")
    w("}\n\n")

    w("/* The names in `mask`, low bit first, as English: \"A\", \"A and B\",\n")
    w(" * \"A, B and C\". Returns `buf`, always NUL-terminated when n > 0.\n")
    w(" * `mask` with no known bit renders \"none\". */\n")
    w("static inline const char *\n")
    w("cft_seq_flag_names(uint32_t mask, char *buf, size_t n)\n")
    w("{\n")
    w("    static const struct { uint32_t bit; const char *name; } defs[] = {\n")
    for bit, name, _c in FLAG_TABLE:
        w('        { 0x%08xu, "%s" },\n' % (bit, name))
    w("    };\n")
    w("    const size_t ndefs = sizeof defs / sizeof defs[0];\n")
    w("    size_t i, used = 0u, count = 0u, seen = 0u;\n")
    w("\n")
    w("    if (n == 0u)\n")
    w("        return buf;\n")
    w("    buf[0] = '\\0';\n")
    w("    for (i = 0u; i < ndefs; i++)\n")
    w("        if (mask & defs[i].bit)\n")
    w("            count++;\n")
    w("    if (count == 0u)\n")
    w('        return (cft_seq_flag_append_(buf, n, 0u, "none"), buf);\n')
    w("    for (i = 0u; i < ndefs; i++) {\n")
    w("        if (!(mask & defs[i].bit))\n")
    w("            continue;\n")
    w("        if (seen != 0u)\n")
    w("            used = cft_seq_flag_append_(buf, n, used,\n")
    w('                                        seen + 1u == count ? " and " : ", ");\n')
    w("        used = cft_seq_flag_append_(buf, n, used, defs[i].name);\n")
    w("        seen++;\n")
    w("    }\n")
    w("    return buf;\n")
    w("}\n\n")

    w("/* Enough room for every defined name plus its separators. */\n")
    total = sum(len(name) for _b, name, _c in FLAG_TABLE)
    total += 5 * max(len(FLAG_TABLE) - 1, 0) + 1
    w("#define CFT_SEQ_FLAG_NAMES_MAX %du\n\n" % total)

    w("#ifdef __cplusplus\n")
    w("}\n")
    w("#endif\n")
    w("#endif /* CFT_SEQ_FLAGS_H */\n")
    return out.getvalue()


def public_bits():
    """Every CFT_PROG_FLAG_* in cft.h, as {name: bit}."""
    text = PUBLIC.read_text(encoding="utf-8")
    pat = re.compile(r"^#define\s+CFT_PROG_FLAG_(\w+)\s+\(1u\s*<<\s*(\d+)\)", re.M)
    return {m.group(1): 1 << int(m.group(2)) for m in pat.finditer(text)}


def check_public():
    """cft.h and the golden model must assign the same bits.

    Both directions: a flag the model defines and cft.h does not is a
    number the C side can assign to something else tomorrow, and a flag
    cft.h defines that the model does not is a contract nothing
    implements.
    """
    have = public_bits()
    want = {name: bit for bit, name, _c in FLAG_TABLE}
    problems = []
    for name, bit in want.items():
        if name not in have:
            problems.append("cft.h does not define CFT_PROG_FLAG_%s (model: %#010x)"
                            % (name, bit))
        elif have[name] != bit:
            problems.append("CFT_PROG_FLAG_%s is %#010x in cft.h, %#010x in the model"
                            % (name, have[name], bit))
    for name, bit in have.items():
        if name not in want:
            problems.append("cft.h defines CFT_PROG_FLAG_%s (%#010x) and the golden "
                            "model does not" % (name, bit))
    return problems


if __name__ == "__main__":
    checking = "--check" in sys.argv[1:]
    text = render()
    problems = check_public()

    if checking:
        on_disk = HEADER.read_text(encoding="utf-8") if HEADER.exists() else None
        if on_disk is None:
            problems.append("%s does not exist; run python/gen_seq_flags.py"
                            % HEADER.name)
        elif on_disk != text:
            problems.append("%s has drifted from python/cft_golden/seqflags.py; "
                            "run python/gen_seq_flags.py" % HEADER.name)
        if problems:
            for p in problems:
                print("gen_seq_flags: %s" % p, file=sys.stderr)
            sys.exit(1)
        print("gen_seq_flags: %s and cft.h agree with the golden model"
              % HEADER.name)
        sys.exit(0)

    if problems:
        for p in problems:
            print("gen_seq_flags: %s" % p, file=sys.stderr)
        sys.exit("gen_seq_flags: cft.h disagrees with the model; not writing")
    io.open(HEADER, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d bytes)" % (HEADER, len(text)))
